# Generated by Django 4.1.4 on 2023-01-03 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfile', '0002_quote_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='file',
        ),
    ]
